INF-416: Rewrite pkg-cache to use SFTP instead of nfs mounted local directories.
Care has been taken to atomically move directories around in order to
avoid race conditions when 2 buildslaves are uploading the same files,
or when one is uploading and one is downloading.

diff --git a/deps-packaging/pkg-cache b/deps-packaging/pkg-cache
--- a/deps-packaging/pkg-cache
+++ b/deps-packaging/pkg-cache
@@ -3,6 +3,9 @@
 . `dirname "$0"`/../build-scripts/functions
 
 
+# TODO KEEP THE OLD VERSION OF LOCAL CACHE FOR WHOEVER DOES NOT WANT REMOTE CACHE
+
+
 # Check for Jenkins node label and use that as index.
 # There can be multiple labels, pick the first one.
 firstlabel=${NODE_LABELS%% *}
@@ -13,8 +16,10 @@ then
     firstlabel=NO_LABEL
 fi
 
-CACHEDIR=$HOME/.cache/cfengine-buildscripts-pkgs/$firstlabel
-
+#CACHEDIR=$HOME/.cache/cfengine-buildscripts-pkgs/$firstlabel
+CACHEDIR=cache/$firstlabel
+CACHEHOST=cfe_pkgs@138.68.18.72
+SFTP="sftp -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey $CACHEHOST  |  grep -v '^sftp>'"
 
 usage()
 {
@@ -28,11 +33,11 @@ usage()
     echo "$0 list <pkg>-<version>-<release>"
     echo "  lists cached package files"
     echo
-    echo "$0 prune <pkg>-<version>-<release>"
-    echo "  removes cached package files"
-    echo
-    echo "$0 autoprune <pkg> <n>"
-    echo "  removes all but the <n> most recently used cached package files"
+    # echo "$0 prune <pkg>-<version>-<release>"
+    # echo "  removes cached package files"
+    # echo
+    # echo "$0 autoprune <pkg> <n>"
+    # echo "  removes all but the <n> most recently used cached package files"
     exit 1
 }
 
@@ -42,13 +47,13 @@ opts()
     then
         usage
     fi
-
     CMD="$1"
     shift
 
+
     case "$CMD" in
 
-    find|list|prune|store)
+    find|list|store)
         PKGVR="$1"
         shift
 
@@ -70,72 +75,46 @@ opts()
                 ;;
         esac
         ;;
-    autoprune)
-        if [ $# -ne 2 ]
-        then
-            usage
-        fi
-        PKG="$1"
-        NUM="$2"
-        shift 2
-        ;;
-    *)
-        fatal "Unknown command: $CMD"
-        ;;
+
+    *)  fatal "Unknown command: $CMD"  ;;
     esac
 }
 
 
 opts "$@"
 
-# Work around the fact that Solaris tail only supports obsolete +n syntax.
-# We need to enable it explicitly for other platforms.
-export _POSIX2_VERSION=1
+
 
 case "$CMD" in
-    find)
-        if [ `find "$PKGCACHEDIR" -type f  |  wc -l`  !=  0 ]
-        then
-            # Update access time for autoprune.
-            touch "$PKGCACHEDIR"
-            exit 0
-        else
-            exit 1
-        fi
-        ;;
-    store)
-        if [ -d "$PKGCACHEDIR" ]
-        then
-            echo "pkg-cache store: Skipping storing package because directory already exists:    $PKGCACHEDIR"  1>&2
-            exit
-        fi
+find)
+    if [ `find "$PKGCACHEDIR" -type f  |  wc -l`  !=  0 ]
+    then
+        # Update access time for autoprune.
+        touch "$PKGCACHEDIR"
+        exit 0
+    else
+        exit 1
+    fi
+    ;;
+store)
+    if [ -d "$PKGCACHEDIR" ]
+    then
+        echo "pkg-cache store: Skipping storing package because directory already exists:    $PKGCACHEDIR"  1>&2
+        exit
+    fi
 
-        mkdir -p "$(dirname $PKGCACHEDIR)"
-        tempdir=`mktempdir "$PKGCACHEDIR.XXXXXX"`
+    mkdir -p "$(dirname $PKGCACHEDIR)"
+    tempdir=`mktempdir "$PKGCACHEDIR.XXXXXX"`
 
-        cp $PKGFILES "$tempdir"
+    cp $PKGFILES "$tempdir"
 
-        # Atomically rename directory, to avoid a very common issue:
-        # package directory only containing the "devel" package but not
-        # the main one, or vice-versa.
-        mv "$tempdir" "$PKGCACHEDIR"
-        ;;
-    list)
-        find "$PKGCACHEDIR" -type f  \
-            ||  fatal "Failed searching $PKGVR in cache"
-        ;;
-    prune)
-        if [ -d "$PKGCACHEDIR" ]
-        then
-            rm -rf "$PKGCACHEDIR"
-        else
-            fatal "Package $PKGVR is not in cache."
-        fi
-        ;;
-    autoprune)
-        for cache_entry in $(ls -dt $CACHEDIR/$PKG-* | tail +$(($NUM+1)))
-        do
-            rm -rf "$cache_entry"
-        done
-        ;;
+    # Atomically rename directory, to avoid a very common issue:
+    # package directory only containing the "devel" package but not
+    # the main one, or vice-versa.
+    mv "$tempdir" "$PKGCACHEDIR"
+    ;;
+list)
+    find "$PKGCACHEDIR" -type f  \
+        ||  fatal "Failed searching $PKGVR in cache"
+    ;;
 esac
